### ISSUE TITLE
can't open file '/drone/src/drone_kubernetes_runner.py'

### ISSUE THREAD

**Issue by mytudan** [naorlivne/drone-kubernetes-apply#152]
+ python drone_kubernetes_runner.py
python: can't open file '/drone/src/drone_kubernetes_runner.py': [Errno 2] No such file or directory

**Comment by naorlivne** [comment]
Hi @mytudan, can you supply more details? where are you seeing this? what configuration are you using?

**Comment by naorlivne** [comment]
NVM found the bug, should be ok in the latest image now, can you retry and confirm?

**Comment by mytudan** [comment]
@naorlivne The latest image no longer has this problem

**Comment by naorlivne** [comment]
Then I'm closing this ticket as it seems like the bug has been resolved
